apiVersion: v2
name: venafi-kubernetes-agent
description: |-
  The Venafi Kubernetes Agent connects your Kubernetes or Openshift cluster to the Venafi Control Plane.
type: application
version: 1.0.0
appVersion: "v1.0.0"
