# Run unit-tests
#
# These actions are skipped for draft PRs.
# See https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/19
name: test-unit
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  unit-tests:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    env:
      GOPRIVATE: github.com/jetstack/venafi-connection-lib
    steps:
      - name: Configure jetstack/venafi-connection-lib repo pull access
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.DEPLOY_KEY_READ_VENAFI_CONNECTION_LIB }}" > ~/.ssh/venafi_connection_lib_id
          chmod 600 ~/.ssh/venafi_connection_lib_id

          cat <<EOT >> ~/.ssh/config
          Host venafi-connection-lib.github.com
          HostName github.com
          IdentityFile ~/.ssh/venafi_connection_lib_id
          IdentitiesOnly yes
          EOT

          cat <<EOT >> ~/.gitconfig
          [url "git@venafi-connection-lib.github.com:jetstack/venafi-connection-lib"]
            insteadOf = https://github.com/jetstack/venafi-connection-lib
          EOT

      - uses: actions/checkout@v4
        with:
          # Full git history is needed to get a Git tags which are used to
          # calculate a valid semver for the Helm chart
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - uses: actions/cache@v4
        with:
          path: _bin/downloaded
          key: downloaded-${{ runner.os }}-${{ hashFiles('make/_shared/tools/00_mod.mk') }}-${{ hashFiles('make/_shared/kind/00_kind_image_versions.mk') }}
      - run: make test-unit
